### ISSUE TITLE
Products are never stored

### ISSUE THREAD

**Issue by uson1x** [recisio/StoreKitCompanion#3]
Hi

If I'm not missing anything the products var

```
private var products = [SKProduct]()
```

never gets updated and therefore adding a payment always failing due to the fact that there is no product with such name (`productWithIdentifier` always returns nil), making it impossible to purchase anything.

**Comment by uson1x** [comment]
So we should either store the fetched products, like in this PR https://github.com/recisio/StoreKitCompanion/pull/4, or do something more complicated.

**Comment by vincedev** [comment]
Merged #4

**Comment by tbaranes** [comment]
Thanks for your PR, we just add some changes to compile on OS X.
CocoaPods is now updated :tada:
