### ISSUE TITLE
[WIP] Swift 3 Migration

### ISSUE THREAD

**Issue by tbaranes** [recisio/StoreKitCompanion#5]
- [x] Swift 3 support
- [ ] Improve naming to respect swift 3 guidelines
- [x] Update travis

**Comment by Skogetroll** [comment]
During this migration huge chunk of source code was commented out without providing any code to replace commented one (like `sendReceiptWithPOSTRequest`).

Will it ever come back?

**Comment by tbaranes** [comment]
Sadly, `StoreKitCompanion` is paused for now (others project have higher priority) which is also the reason that we take so much time to merge the migration PR, but we'll definitely review any PRs if you want to work on this.
Otherwise, you can also use [StoreKitCompanion](https://github.com/recisio/StoreKitCompanion) which has all the features from `StoreKitCompanion` and even more.
